services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin
    container_name: jellyfin
    #user: uid:gid
    #network_mode: 'host'
    ports:
      - 8096:8096
      - 8920:8920 #optional - for https
      - 7359:7359/udp #optional - for DLNA
    volumes:
      - ~/homelab/jellyfin/config:/config
      - ~/homelab/jellyfin/cache:/cache
      - type: bind
        source: /bazen-large/bazen-large
        target: /media
        read_only: true
      - type: bind
        source: /bazen-raid/bazen-raid
        target: /media2
        read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      #- type: bind
      #  source: /path/to/fonts
      #  target: /usr/local/share/fonts/custom
      #  read_only: true
    restart: always
    # Optional - alternative address used for autodiscovery
    #environment:
    #  - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    #extra_hosts:
    #  - 'host.docker.internal:host-gateway'